### PR TITLE
xbox: Run constructors in main thread, provide mechanism for old way

### PR DESCRIPTION
**Pull request by thrimbor**
This changes our startup code to run constructors in the main thread instead of the startup thread. This is necessary because constructors might require functional thread-local storage, which is not available from the startup thread, causing issues such as https://github.com/XboxDev/nxdk/issues/496

This change alone will lead to crashes if not combined with the change in https://github.com/XboxDev/nxdk/pull/497.

### CODE REVIEW

**Comment by JayFoxRox** [comment]
1. What is meant by "provide mechanism for old way"?
2. Shouldn't the name reflect that these are being ran on a different thread?
3. Do we also need this for C-style initializers?


Unrelated to this PR: that `assert(ret == 0)` in `_PDCLIB_xbox_run_crt_initializers` looks out of place?

**Comment by thrimbor** [comment]
>     1. What is meant by "provide mechanism for old way"?
Executing function pointers in the `.CRT$XX` section. I should probably split the commit and improve the wording.

>     2. Shouldn't the name reflect that these are being ran on a different thread?
Probably, but I couldn't come up with a descriptive yet unobtrusive name so far.

>     3. Do we also need this for C-style initializers?
To use this, a function pointer needs to get manually put into this section, so we can dictate the return value type etc. and should be fine with only providing this.

I'm also not fully sure our terminology of C-style and C++-style is correct here - the MSDN only talks about initializers in the context of C++, so I based this on third-party information (the osdev.org article on C++ and some implementations of "mini-CRTs" for MSVC). However, I haven't been able to get clang/LLVM to emit a C-style initializer, functions marked as constructors end up in the `.CRT$XC` section, no matter whether they come from C or C++ code.
I haven't yet been able to go down the rabbit hole of checking whether MSVC does the same and how they run this stuff.

> Unrelated to this PR: that `assert(ret == 0)` in `_PDCLIB_xbox_run_crt_initializers` looks out of place?

Agreed, this was based on the same third-party info I mentioned above. It makes no real sense this way, and should get checked against MSVC behavior (ReactOS seems to completely ignore the return value).

**Comment by thrimbor** [comment]
> > Unrelated to this PR: that `assert(ret == 0)` in `_PDCLIB_xbox_run_crt_initializers` looks out of place?
> 
> Agreed, this was based on the same third-party info I mentioned above. It makes no real sense this way, and should get checked against MSVC behavior (ReactOS seems to completely ignore the return value).

Actually, it's fine like this already. It also matches what MSVC does, except we're using assert instead of terminating the program.

I did split the commit and improved the wording though.

**Comment by thrimbor** [comment]
Without this fix, global constructors are broken in C++, so I'll probably self-merge this soon.

**Pull request merged**
