### PR TITLE
Update to current upstream PDCLib

### PR DESCRIPTION
**Pull request by thrimbor**
In addition to the changes listed in #4, there are additional fixes related to properly unlocking filestream mutexes and `exit()` now properly closing files. Additionally, there's now a single dlmalloc copy in the repo.

Since #4 has been sitting for a while now and changes to nxdk-specific code in this PR are minimal, I intend to merge this soon-ish if there are no remarks.

This PR cannot be merged automatically - instead, I intend to take the route I proposed in Discord, which means I'll add a tag to the current HEAD of the nxdk-branch and then replace it with this one (which leads to a *much* cleaner history).

/edit:
Oh, and like @LukeUsher suggested, we now get rid of the startup-thread in `XboxCRTEntry()`, since there's little reason to keep it around as the main-function is run in a new thread anyway (it used to just block waiting for the main()-thread).

### CODE REVIEW

**Comment by dracc** [comment]
I intend to test this soon (as in "later today").
Initial feeling is that startup thread removal might have been fit for its own PR.

**Comment by thrimbor** [comment]
> Initial feeling is that startup thread removal might have been fit for its own PR.

That was my original intent, but given that the `exit()`-fix (which is necessary to ensure proper cleanup) essentially makes this dead code means that, if we don't detach, we leak the thread handle, I decided to clean this up in one go (the kernel would clean up the leak anyway, but still).

I made completely sure to test this specific change with all samples on my Xbox and XQEMU because I was afraid the return from `XboxCRTEntry()` might break something - even though @LukeUsher said that XAPI does it that way, there's always the chance that we got the calling convention wrong or something (seems fine though).

**Comment by dracc** [comment]
I've now tested with XQEMU, no new odd behavior in NevolutionX caused by this. :+1:
Will test on my 1.6 Xbox in approx. 6h.

**Comment by dracc** [comment]
No visible change in run-ability on my 1.6 :+1:

**Review by dracc — APPROVED** [review]

**Comment by thrimbor** [comment]
Unless there's any feedback I intend to merge this later today.

**Pull request merged**
