### PR TITLE
Move libc file functions from X*FIle* to Win32 API

### PR DESCRIPTION
**Pull request by sam-itt**
... and finally have a working feof() !

### CODE REVIEW

**Comment by JayFoxRox** [comment]
This does the same as #15 (also see discussion as to why that wasn't merged yet).

**Comment by sam-itt** [comment]
Ok then. Problem was/is: feof doesn't work because XReadFile doesn't set the flag. I didn't go fixing it because of the deprecated tag.

When do you plan to merge #15 ? My code depends on standard file functions and It'll be nice to be able to build it using "mainline" nxdk.

**Comment by JayFoxRox** [comment]
> My code depends on standard file functions and It'll be nice to be able to build it using "mainline" nxdk.

That's a good mindset (pushes development forward in upstream; also thanks for your upstream pdclib contributions!). I'm in a similar position and would like to use upstream nxdk for all of my projects.

> When do you plan to merge #15 ?

I'm not sure: Merging it as-is will break many applications and ports currently in development.
But also it has been there since November and nobody seems to have cared for reviewing it.
I'd like to get a second review or at least opinion on my review by others, as I can only state my opinion (but XboxDev should be a community effort).

I'm personally leaning towards accepting it soonish (possibly with minor changes?) and iterating on it later. People could still revert to the old code or check out an older nxdk as fallback.

**Comment by JayFoxRox** [comment]
I'm closing this as #15 had adapted code from this already. That will also be merged later today unless there's some serious issue.

**Pull request closed without merging**
