### PR TITLE
Fixed an error

### PR DESCRIPTION
**Pull request by PQCraft**
`#pragma STDC FENV_ACCESS ON` on line 4 of `platform/xbox/functions/math/nearbyint.c` causes
```
/home/pqcraft/Documents/git/nxdk//lib/pdclib/platform/xbox/functions/math/nearbyint.c:4:14: error: '#pragma STDC FENV_ACCESS ON' is illegal when precise is disabled
#pragma STDC FENV_ACCESS ON
             ^
1 warning and 1 error generated.
```

### CODE REVIEW

**Comment by thrimbor** [comment]
That's not an error - we need that because we're dealing with floating point exception flags here. You're probably trying to build all of nxdk with fast math, which is not supported.

**Comment by PQCraft** [comment]
Nah I don't have fast math enabled
And the only flags I pass are `-g -Og`
No `-ffast-math` or `-Ofast`

**Comment by thrimbor** [comment]
Please post a log (`make V=1`) of a failing compilation run and clang version info (`clang --version`). There's either a compiler bug here or something is modifying the default floating point behavior.

**Comment by PQCraft** [comment]
[Build log](https://github.com/XboxDev/nxdk-pdclib/files/12114908/buildlog.txt) (error happens on line 1386)
Clang version:
```
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by thrimbor** [comment]
That's the normal log, I need the `make V=1` log

**Comment by thrimbor** [comment]
` -pthread -ffast-math`
There's your problem, these are not valid parameters to build nxdk with.

**Comment by PQCraft** [comment]
oh i might of just learned something new about makefile

**Comment by PQCraft** [comment]
yep today i learned that it evals the vars *then* evals the rules
i thought it would just eval the rules and vars at the same time

**Comment by PQCraft** [comment]
welp i guess that's all folks

**Pull request closed without merging**
